name: flutter_unified_image_picker
description: "A powerful Flutter plugin for **camera capture** and **gallery selection** with a draggable bottom sheet. Fully decoupled architecture using **CameraService**, **GalleryService**, and **BottomSheetService**, all managed by `ImagePickerController`."
version: 1.0.0
homepage: https://github.com/mirzamahmud/flutter_unified_image_picker
repository: https://github.com/mirzamahmud/flutter_unified_image_picker
issue_tracker: https://github.com/mirzamahmud/flutter_unified_image_picker/issues
documentation: https://github.com/mirzamahmud/flutter_unified_image_picker#readme

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  permission_handler: ^12.0.1
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.mirza.flutter_unified_image_picker
        pluginClass: FlutterUnifiedImagePickerPlugin
      ios:
        pluginClass: FlutterUnifiedImagePickerPlugin
